# Generated by Django 4.1.7 on 2023-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='imageData',
            field=models.FileField(upload_to=''),
        ),
    ]
