# Generated by Django 4.1.7 on 2023-02-20 23:39

from django.db import migrations, models
import kidsart.models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='image_url',
            field=models.ImageField(upload_to=kidsart.models.upload_to),
        ),
    ]
