# Generated by Django 4.1.7 on 2023-02-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsart', '0002_alter_artpiece_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
